# Generated by Django 6.0.3 on 2026-05-28 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interes_credito', models.FloatField(default=18)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('linea', models.CharField(max_length=100, null=True)),
                ('modelo', models.CharField(max_length=4, null=True)),
                ('precio', models.IntegerField()),
                ('cilindraje', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='motos/')),
                ('kilometraje', models.IntegerField(default=0)),
                ('descripcion', models.CharField(default='Sin descripción', max_length=500)),
                ('placa', models.CharField(default='Sin placa', max_length=10)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('descripcion_larga', models.TextField(default='Sin información')),
                ('soat', models.CharField(default='No especificado', max_length=100)),
                ('tecnomecanica', models.CharField(default='No especificado', max_length=100)),
                ('transito', models.CharField(default='No especificado', max_length=100)),
                ('destacado', models.BooleanField(default=False)),
                ('vistas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='motos/galeria/')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='motos.moto')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motos.moto')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(default='perfiles/default.png', upload_to='perfiles/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('whatsapp', models.CharField(max_length=30)),
                ('kilometraje', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='solicitudes/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
