# Generated by Django 6.0.3 on 2026-06-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
